### PR TITLE
Update dependencies to fix vulnerabiity related to js-yaml

### PR DESCRIPTION
**Pull request by tomap**

### CODE REVIEW

**Comment by tomap** [comment]
With the last release of hexo, no need to push the package-lock

**Comment by ertrzyiks** [comment]
According to https://docs.npmjs.com/files/package-lock.json

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package

Means that it will never get into the published package. It may be still useful for development, though. I would rather keep in it the repo.

What so special about the latest hexo version that would make us drop it from the repo?

**Comment by itpropro** [comment]
I am in general no fan of the package-lock.json file. It just makes working in a team a lot more complicated and troubleshooting old version is a pain when you need to compare multiple versions of package-lock. All development teams I know that are working with multiple people on a complex product completely disabled the package-lock. If you need it for development to reproduce a certain point in time, just archive it from your build pipeline artifacts.

**Comment by tomap** [comment]
Well then, what shall we do here?

**Comment by ertrzyiks** [comment]
I need some lock for development, not to reproduce a certain point in time as @itpropro said but to be able to immediately start work after a long break to avoid dealing with dev dependencies conflicts. 

Let's make removal of the package lock good opportunity to migrate this repo to yarn.

**Pull request merged**
